name: Test logging framework

on: [push, pull_request]

jobs:
  run_unit_tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run all unit tests
        run: mvn clean test